export const ADD_EMP =        "ADD_EMP         ";
export const DELETE_EMP =     "DELETE_EMP      ";
export const UPDATE_EMP =     "UPDATE_EMP      ";
export const SET_CURRENT_EMP ="SET_CURRENT     ";
export const FILTER_EMP =     "FILTER_EMP      ";
export const CLEAR_FILTER_EMP="CLEAR_FILTER_EMP";
export const SET_ALERT       ="SET_ALERT       ";
export const CLEAR_ALERT     ="CLEAR_ALERT     ";
export const CLEAR_CURRENT_EMP = " CLEAR_CURRENT_EMP ";